name: Mirror Repo for Vercel

on:
  push:
    branches:
      - main # Triggers when you push to main on this client repo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          persist-credentials: false

      - name: Push to Secondary Personal Repo
        env:
          TARGET_REPO: ${{ secrets.TARGET_REPO }} # Format: "your-username/your-new-repo"
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Remove GitHub workflows from the codebase in the runner
          git rm -rf --ignore-unmatch .github/workflows/
          git commit -m "chore: remove github workflows for secondary repo" || true
          
          git remote add secondary https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git
          git push secondary HEAD:main --force
