name: Mirror Repo for Vercel

on:
  push:
    branches:
      - main # Triggers when you push to main on this client repo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          persist-credentials: false

      - name: Push to Secondary Personal Repo
        env:
          TARGET_REPO: ${{ secrets.TARGET_REPO }} # Format: "your-username/your-new-repo"
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
        run: |
          # Set the identity to the user who triggered the action (to be the sole contributor)
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          # Create a new branch with no commit history
          git checkout --orphan vercel_sync
          
          # Remove GitHub workflows from the codebase in the runner
          git rm -rf --ignore-unmatch .github/workflows/
          
          # Commit the entire current state as a single commit
          git commit -m "chore: sync code to Vercel"
          
          # Push this single commit to the main branch of the secondary repo, overwriting everything
          git remote add secondary https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git
          git push secondary vercel_sync:main --force
